Repository WholeSeeds/Mindle-Server, pull requests merged in 2025-07, with the labels that each got.

#20 [Feat] #15 회원 API 구현, Firebase 인증 인터셉터 개선
  src/main/java/com/wholeseeds/mindle/common/annotation/CurrentMember.java
  src/main/java/com/wholeseeds/mindle/common/repository/JpaBaseRepositoryImpl.java
  src/main/java/com/wholeseeds/mindle/common/response/ErrorCode.java
  src/main/java/com/wholeseeds/mindle/config/LogBackConfig.java
  src/main/java/com/wholeseeds/mindle/config/WebConfig.java
  src/main/java/com/wholeseeds/mindle/domain/auth/exception/InvalidTokenException.java
  src/main/java/com/wholeseeds/mindle/domain/auth/exception/MissingCurrentMemberException.java
  src/main/java/com/wholeseeds/mindle/domain/auth/exception/MissingTokenException.java
  src/main/java/com/wholeseeds/mindle/domain/auth/service/FirebaseAuthService.java
  src/main/java/com/wholeseeds/mindle/domain/complaint/repository/CategoryRepository.java
  src/main/java/com/wholeseeds/mindle/domain/complaint/repository/ComplaintImageRepository.java
  src/main/java/com/wholeseeds/mindle/domain/complaint/repository/ComplaintRepository.java
  src/main/java/com/wholeseeds/mindle/domain/complaint/service/ComplaintService.java
  src/main/java/com/wholeseeds/mindle/domain/location/entity/City.java
  src/main/java/com/wholeseeds/mindle/domain/location/entity/District.java
  src/main/java/com/wholeseeds/mindle/domain/location/entity/Subdistrict.java
  src/main/java/com/wholeseeds/mindle/domain/location/exception/CityNotFoundException.java
  src/main/java/com/wholeseeds/mindle/domain/location/exception/DistrictNotFoundException.java
  src/main/java/com/wholeseeds/mindle/domain/location/exception/SubdistrictNotFoundException.java
  src/main/java/com/wholeseeds/mindle/domain/location/repository/CityRepository.java
  src/main/java/com/wholeseeds/mindle/domain/location/repository/DistrictRepository.java
  src/main/java/com/wholeseeds/mindle/domain/location/repository/SubdistrictRepository.java
  src/main/java/com/wholeseeds/mindle/domain/member/controller/MemberController.java
  src/main/java/com/wholeseeds/mindle/domain/member/dto/request/UpdateNicknameRequestDto.java
  src/main/java/com/wholeseeds/mindle/domain/member/dto/request/UpdateSubdistrictRequestDto.java
  src/main/java/com/wholeseeds/mindle/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/wholeseeds/mindle/domain/member/entity/Member.java
  src/main/java/com/wholeseeds/mindle/domain/member/exception/DuplicateNicknameException.java
  src/main/java/com/wholeseeds/mindle/domain/member/repository/custom/MemberRepositoryCustom.java
  src/main/java/com/wholeseeds/mindle/domain/member/repository/impl/MemberRepositoryImpl.java
  src/main/java/com/wholeseeds/mindle/domain/member/service/MemberService.java
  src/main/java/com/wholeseeds/mindle/domain/place/repository/PlaceRepository.java
  src/main/java/com/wholeseeds/mindle/global/interceptor/FirebaseAuthInterceptor.java
  src/main/java/com/wholeseeds/mindle/global/interceptor/LoggingInterceptor.java
  src/main/java/com/wholeseeds/mindle/global/interceptor/RequireAuthInterceptor.java
  src/main/java/com/wholeseeds/mindle/global/resolver/CurrentMemberArgumentResolver.java
  src/main/java/com/wholeseeds/mindle/infra/service/NcpObjectStorageService.java
  src/main/resources/application.yml
Labels: ⭐️ Feature

#24 [Fix] #23 CommonCode 중복 코드 제거
  src/main/java/com/wholeseeds/mindle/common/code/CommonCode.java
  src/main/java/com/wholeseeds/mindle/common/util/ObjectUtils.java
  src/main/java/com/wholeseeds/mindle/domain/complaint/controller/ComplaintController.java
  src/main/java/com/wholeseeds/mindle/domain/complaint/service/ComplaintService.java
Labels: 🔧 Fix

#26 #25 회원 알림 설정 API, 회원 탈퇴 API 구현, CurrentMemberId
  src/main/java/com/wholeseeds/mindle/common/annotation/CurrentMemberId.java
  src/main/java/com/wholeseeds/mindle/common/entity/BaseEntity.java
  src/main/java/com/wholeseeds/mindle/config/WebConfig.java
  src/main/java/com/wholeseeds/mindle/domain/location/dto/SubdistrictDto.java
  src/main/java/com/wholeseeds/mindle/domain/member/controller/MemberController.java
  src/main/java/com/wholeseeds/mindle/domain/member/dto/request/UpdateNotificationSettingRequestDto.java
  src/main/java/com/wholeseeds/mindle/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/wholeseeds/mindle/domain/member/entity/Member.java
  src/main/java/com/wholeseeds/mindle/domain/member/enums/NotificationType.java
  src/main/java/com/wholeseeds/mindle/domain/member/mapper/MemberMapper.java
  src/main/java/com/wholeseeds/mindle/domain/member/repository/custom/MemberRepositoryCustom.java
  src/main/java/com/wholeseeds/mindle/domain/member/repository/impl/MemberRepositoryImpl.java
  src/main/java/com/wholeseeds/mindle/domain/member/service/MemberService.java
  src/main/java/com/wholeseeds/mindle/global/interceptor/RequireAuthInterceptor.java
  src/main/java/com/wholeseeds/mindle/global/resolver/CurrentMemberIdArgumentResolver.java
Labels: ⭐️ Feature

#28 refactor #18 : mindle-secret.json 외부에서 마운트하도록 수정
  deployment.yaml
  src/main/resources/application-prod.yml
Labels: 🌏 Deploy

#29 refactor #18 : application.yml 에 prod 코드 병합
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🌏 Deploy
